# Generated by Django 2.1.7 on 2020-07-28 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_post_is_draft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pep',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.TextField(null=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('privacy_type', models.CharField(choices=[('FRIENDS', 'friends'), ('FOLLOWERS', 'followers')], default='FRIENDS', max_length=20)),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pep_example', to='posts.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pep', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cerated_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=20, unique=True)),
                ('peps', models.ManyToManyField(related_name='peps', to='pep.Pep')),
            ],
        ),
    ]
