# Generated by Django 2.1.7 on 2020-04-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200412_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default='null', max_length=500, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
