# Generated by Django 2.1.7 on 2020-05-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('group_type', models.CharField(choices=[('PUBLIC', 'public'), ('PRIVATE', 'private')], default='PRIVATE', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
