# Generated by Django 2.1.7 on 2020-05-14 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('group_type', models.CharField(choices=[('PUBLIC', 'public'), ('PRIVATE', 'private')], default='PRIVATE', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_owned', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='groups_part_of', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
