# Generated by Django 2.1.7 on 2020-08-05 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('FRIEND_REQUEST_SENT', 'friend_request'), ('FOLLOWING', 'following')], max_length=20)),
                ('type', models.CharField(choices=[('NOTIFICATION', 'notification'), ('DATA_MSG', 'data_msg')], default='NOTIFICATION', max_length=20)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='received_notifs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
