# Generated by Django 2.2.15 on 2020-08-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20200807_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='item_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('FRIEND_REQUEST_SENT', 'friend_request_sent'), ('FOLLOWING', 'following'), ('FRIEND_REQUEST_ACCEPTED', 'friend_request_accepted'), ('COMMENTED', 'commented'), ('NOMINATED', 'nominated'), ('RECOMMENDED_POST', 'recommended_post'), ('RECOMMENDED_PEP', 'recommended_pep'), ('TAGGED', 'tagged')], max_length=20),
        ),
    ]
