# Generated by Django 2.1.7 on 2019-05-01 17:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20190404_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCourt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100, null=True)),
                ('cover_pic', models.ImageField(upload_to='userprofiles/foodcourt_pics')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='longitude/latitude')),
                ('phone_number', models.CharField(max_length=10)),
                ('website_url', models.URLField(default='', max_length=100)),
                ('city', models.CharField(default='Banglore', max_length=50)),
            ],
            managers=[
                ('gis', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='foodcourt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='restaurants.FoodCourt'),
        ),
    ]
