# Generated by Django 2.1.7 on 2019-05-02 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20190502_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='foodcourt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='restaurants.FoodCourt'),
        ),
    ]
