# Generated by Django 2.1.7 on 2019-05-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_auto_20190502_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcourt',
            name='cover_pic',
            field=models.ImageField(upload_to='media/foodcourt_pics'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cover_pic',
            field=models.ImageField(upload_to='media/restaurant_pics'),
        ),
    ]
