# Generated by Django 2.1.7 on 2019-05-03 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_auto_20190503_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'menu', 'verbose_name_plural': 'menu'},
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='restaurants.Restaurant'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='classification',
            field=models.CharField(choices=[('non-vegetarian', 'Non-Vegetarian'), ('vegan', 'Vegan'), ('vegetarian', 'Vegetarian')], default=0, help_text='Select if this item classifies as Vegetarian, Vegan, or Neither.', max_length=10, verbose_name='classification'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, help_text='The image is an optional field that is associated with each menu item.', null=True, upload_to='media/menu_item_pics', verbose_name='image'),
        ),
    ]
