# Generated by Django 2.1.7 on 2019-05-04 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_auto_20190503_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='popular',
            field=models.BooleanField(default=False, help_text='Is this item popular?', verbose_name='Popular?'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='menu',
            field=models.ForeignKey(help_text="The menus that this category belongs to, i.e. 'Lunch'.", on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurants.Menu'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ManyToManyField(help_text="Category is the menu category that this menu item belongs to, i.e. 'Appetizers'.", related_name='categories', to='restaurants.MenuCategory', verbose_name='menu category'),
        ),
    ]
