# Generated by Django 2.1.7 on 2019-05-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_auto_20190504_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ManyToManyField(help_text="Category is the menu category that this menu item belongs to, i.e. 'Appetizers'.", related_name='items', to='restaurants.MenuCategory', verbose_name='menu category'),
        ),
    ]
