# Generated by Django 2.1.7 on 2019-08-02 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_auto_20190507_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantprofile',
            name='merchant',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='paytm.MerchantProfile'),
        ),
        migrations.DeleteModel(
            name='MerchantProfile',
        ),
    ]
