# Generated by Django 2.1.7 on 2019-08-02 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_auto_20190802_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='merchant',
            new_name='paytm_merchant',
        ),
    ]
