# Generated by Django 2.1.7 on 2019-08-03 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0021_auto_20190803_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
