# Generated by Django 2.1.7 on 2019-08-03 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0024_remove_quantity_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='restaurants.Order'),
        ),
    ]
