# Generated by Django 2.1.7 on 2019-08-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0026_auto_20190819_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
