# Generated by Django 2.1.7 on 2020-04-13 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialAuth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentialsmodel',
            name='id',
        ),
        migrations.DeleteModel(
            name='CredentialsModel',
        ),
    ]
