# Generated by Django 2.1.7 on 2019-05-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytmhistory',
            name='BANKTXNID',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='BANK TXN ID'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='GATEWAYNAME',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='GATEWAY NAME'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='MID',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='ORDERID',
            field=models.CharField(max_length=50, verbose_name='ORDER ID'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='RESPCODE',
            field=models.CharField(max_length=10, verbose_name='RESP CODE'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='STATUS',
            field=models.CharField(max_length=20, verbose_name='STATUS'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='TXNAMOUNT',
            field=models.CharField(max_length=10, verbose_name='TXN AMOUNT'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='TXNID',
            field=models.CharField(max_length=64, verbose_name='TXN ID'),
        ),
    ]
