# Generated by Django 2.1.7 on 2019-08-02 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paytm', '0002_auto_20190511_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('mid', models.CharField(max_length=20, unique=True)),
                ('key', models.CharField(max_length=20, unique=True)),
                ('merchant', models.OneToOneField(help_text="The menus that this category belongs to, i.e. 'Lunch'.", on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
