# Generated by Django 2.1.7 on 2019-08-02 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paytm', '0003_merchantprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchantprofile',
            old_name='merchant',
            new_name='owner',
        ),
    ]
