# Generated by Django 2.1.7 on 2019-08-02 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paytm', '0005_auto_20190802_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchantprofile',
            old_name='mid',
            new_name='merchant_id',
        ),
    ]
