# Generated by Django 2.1.7 on 2019-08-04 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paytm', '0006_auto_20190802_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paytmhistory',
            name='user',
        ),
        migrations.AddField(
            model_name='paytmhistory',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paytm_history', to='paytm.MerchantProfile'),
        ),
    ]
