# Generated by Django 2.1.7 on 2019-08-04 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paytm', '0007_auto_20190804_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paytmhistory',
            name='merchant',
        ),
        migrations.AddField(
            model_name='paytmhistory',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paytm_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
