# Generated by Django 2.1.7 on 2019-08-19 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paytm', '0008_auto_20190804_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantprofile',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='merchantprofile',
            name='owner',
            field=models.OneToOneField(help_text='The User this restaurant belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='paytm_merchant', to=settings.AUTH_USER_MODEL),
        ),
    ]
