# Generated by Django 2.1.7 on 2020-05-21 00:14

from django.db import migrations, models
import django.db.models.deletion
import smartfields.fields
import smartfields.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('bookmark_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('bookmark_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('comment_type', models.CharField(choices=[('TEXT', 'text'), ('IMAGE', 'image'), ('STICKER', 'sticker')], default='TEXT', max_length=7)),
                ('text', models.TextField(null=True)),
                ('commentSrc', models.ImageField(upload_to='comment_images_stickers')),
            ],
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('hashtag_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('hashtag_time', models.DateTimeField(auto_now_add=True)),
                ('hashtag', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('like_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('image', smartfields.fields.ImageField(upload_to='post')),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('location', models.TextField(null=True)),
            ],
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PostTags',
            fields=[
                ('post_tag_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileViews',
            fields=[
                ('view_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('view_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('recommend_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('recommend_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='posts.Post')),
            ],
        ),
    ]
