# Generated by Django 2.1.7 on 2020-05-14 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('hashtag_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('hashtag_time', models.DateTimeField(auto_now_add=True)),
                ('hashtag', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('like_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('imgSrc', models.ImageField(upload_to='media/post_pics')),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('location', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostTags',
            fields=[
                ('post_tag_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tags', to='posts.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileViews',
            fields=[
                ('view_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('view_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('view_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_views', to=settings.AUTH_USER_MODEL)),
                ('view_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('recommend_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('recommend_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('recommend_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_recommendatiions', to=settings.AUTH_USER_MODEL)),
                ('recommend_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommends', to='posts.Post')),
                ('recommend_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_recommendatiions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tag_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to=settings.AUTH_USER_MODEL),
        ),
    ]
