# Generated by Django 2.1.7 on 2020-05-15 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('comment_type', models.CharField(choices=[('TEXT', 'text'), ('IMAGE', 'image'), ('STICKER', 'sticker')], default='TEXT', max_length=7)),
                ('text', models.TextField(null=True)),
                ('commentSrc', models.ImageField(upload_to='comment_images_stickers')),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.Post')),
            ],
        ),
    ]
