# Generated by Django 2.1.7 on 2020-05-21 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommend_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_recommendatiions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommend_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommends', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommend_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_recommendatiions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profileviews',
            name='view_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profileviews',
            name='view_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posttags',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tags', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='posttags',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='posts',
            field=models.ManyToManyField(related_name='hashtags', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
