# Generated by Django 2.1.7 on 2020-07-28 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pep', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_post_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nominees',
            field=models.ManyToManyField(related_name='nominees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='pep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', to='pep.Pep'),
        ),
    ]
