# Generated by Django 2.1.7 on 2020-05-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200521_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('PUBLIC', 'public'), ('PRIVATE', 'private')], default='PRIVATE', max_length=7),
        ),
    ]
