# Generated by Django 2.1.7 on 2020-05-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_post_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
        migrations.AddField(
            model_name='post',
            name='privacy_type',
            field=models.CharField(choices=[('FRIENDS', 'friends'), ('FOLLOWERS', 'followers')], default='FRIENDS', max_length=7),
        ),
    ]
