# Generated by Django 2.1.7 on 2020-05-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200521_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='privacy_type',
            field=models.CharField(choices=[('FRIENDS', 'friends'), ('FOLLOWERS', 'followers')], default='FRIENDS', max_length=20),
        ),
    ]
