# Generated by Django 2.1.7 on 2020-05-17 14:57

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200516_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imgSrc',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=smartfields.fields.ImageField(default='null', upload_to='post'),
            preserve_default=False,
        ),
    ]
